# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PodExample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
end

  # Pods for PodExample
  pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git', :branch => 'swift-3'

  target 'PodExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PodExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
